CREATE DATABASE CLASSROOM;
USE CLASSROOM;
CREATE TABLE STUDENT(ID INT,NAME VARCHAR(30),MOBILE BIGINT);
DESC STUDENT;
ALTER TABLE STUDENT ADD ADDRESS VARCHAR(30);
ALTER TABLE STUDENT MODIFY COLUMN ID BIGINT;
DESC STUDENT;