create database codegnan4;
use codegnan4;
create table student_data(id int not null,stuname varchar(50),stusubject varchar(10) not null,marks int default 0);
desc student_data;
insert into student_data values(1,"sai","english",90),(1,"sai","maths",40),(1,"sai","social",89);
select * from student_data;
insert into student_data values(2,"abhi","english",99),(2,"abhi","maths",90),(2,"abhi","social",99);
insert into student_data values(3,"sigma","english",98),(3,"sigma","maths",89),(3,"sigma","social",87);
insert into student_data values(4,"mamul","english",46),(4,"mamul","maths",56),(4,"mamul","social",45);
insert into student_data values(5,"sagar","english",56),(5,"sagar","maths",34),(5,"sagar","social",35);
insert into student_data values(6,"darling","english",24),(6,"darling","maths",24),(6,"darling","social",46);
select * from student_data;
select sum(id) from student_data where id=4;
select count(id) from student_data;
select avg(marks) from student_data;
select min(marks) from student_data;
select max(marks) from student_data;
select * from student_data;
select count(name) from student_data;
select id,sum(marks) from student_data group by id;
select id,sum(marks) as total_marks from student_data group by id;
select id,sum(marks) as english_marks from student_data where subject=english;
select id,marks from student_data where stusubject="english";
select id,stuname,sum(marks) as total_marks from student_data group by id,stuname;
select id,stuname,sum(marks) as total_marks from student_data group by id,stuname having total_marks>150;
select * from final_marks;
insert into final_marks select id,stuname,sum(marks) as total_marks from student_data group by id,stuname;
select * from final_marks;

create database infosys;
use infosys;
create table persons(id int not null,pername varchar(300),persalary varchar(300));
select * from persons;
insert into persons values(1,"abhi",10000),(1,"abhi",15000);
insert into persons values(1,"abhi",10000),(1,"abhi",15000);
insert into persons values(2,"sagar",3000),(2,"sagar",2000);
insert into persons values(3,"bangu",30000),(3,"bangu",45000);
insert into persons values(4,"sigma",23000),(4,"sigma",24000);
select * from persons;
select count(id) from persons;
select sum(id) from persons;
select sum(persalary) from persons;
select avg(persalary) from persons where persalary=24000;
select min(persalary) from persons;
select max(pername) from persons;
select max(id) from persons;
select id,sum(persalary) from persons group by id;


