use amazon;
create table emp(id int,name varchar(200),city varchar(200));
insert into emp values(1,"abhi","ananthapur"),(2,"sigma","kadapa"),(3,"bangaram","kadapo"),(4,"abhi","narpala"),(5,"sigma","kadopa");
select * from emp;
select concat(name," place ",city) as details from emp;
select concat("sai"," ","vardhan") as fullname;
select concat(name, " belongs to ",city) as details from emp;
select concat_ws(",",name,city) as details from emp;
select concat_ws(",",id,name,city) as details from emp;
select upper("abhi") as upper from emp;
select upper("sagar") as upper from emp;
select upper("abhi") as capital from emp;
select lower("ABHI") as lower;
select id,length(name) as namelength,char_length(name) as namecharlength from emp;
select length(city) as city from emp;
select char_length(name) as charnamelength from emp;
select name,substring("abhi",1,3) as substr from emp;
select substring("sagar",1,3) as substr;
select substring("rudrapuabhinayasree",3,10) as substr;
select substring("kummaribhaavanisagar",5,5) as substr;
select name,reverse(name) as revname from emp;
select city,reverse(city) as revname from emp;
select name,city,replace(name,"abhi","ab") as replaced_string from emp;
select id,name,city,replace(name,"sigma","sagar") as replaced_string from emp;
select * from emp where city like "anantha_ur";
select * from emp where city like "an%";
create table emp11(id int key auto_increment,name varchar(300),livingplace varchar(500),fieldname varchar(300));
insert into emp11(name,livingplace,fieldname) values ("abhinaya","hyderabad","hostel"),("bhavanisagar","andhrapradesh","boyshostel"),("upparibharath","nadhyala","house"),("abhilashreddy","kachiguda","room");
select * from emp11;
select name,concat("abhi","naya") as newname from emp11;
select concat("bhavbani","sagar") as newname;
select concat("andhra"," ","pradesh") as newname from emp11;
select name,livingplace,fieldname,concat_ws(",","abhinaya","hyderabad","hostel") as newvalues from emp11;
select name,livingplace,concat_ws(",","abhinaya","hyderabad") as newvalues from emp11;
select lower("abhinaya") as lower;
select upper('bhavanisagar') as capital;
select livingplace,length("hyderabad") as newlength from emp11;
select length("andhrapradesh") as newlength;
select fieldname,char_length("hostel") as newcharlength from emp11;
select name,substring("upparibharath",3,9) as newsubstring from emp11;
select livingplace,reverse("abhinaya") as newname from emp11;
select fieldname,replace(fieldname,"hostel","house") as newname from emp11;
select fieldname,replace(fieldname,"room","house") as newname from emp11;
select * from emp11 where name like "abhi%";
select * from emp11 where name like "bhavanis___r";
select "abhinayasree" like "%sree" as abc;
